logging:
  level:
    root: INFO
    digital.medicina: DEBUG
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/internal_medicine
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
