services:
  mariadb:
    image: mariadb:11
    container_name: internal_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: internal_medicine
      MARIADB_USER: username
      MARIADB_PASSWORD: password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mariadb_data: